name: rapid_mixer
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  sizer: ^2.0.15
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  file_picker: ^10.2.0
  just_audio: ^0.10.4
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.0.0
  http: ^1.1.0
  uuid: ^4.2.1
  crypto: ^3.0.3
  mime: ^1.0.4
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  audioplayers: ^5.2.1
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/instruments/
    - assets/effects/
